name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: typos-action
      uses: crate-ci/typos@v1.0.4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - uses: mbrobbel/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: rustup component add clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
