name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: typos-action
      uses: crate-ci/typos@v1.0.4
    - name: rust-rustfmt-check
      uses: mbrobbel/rustfmt-check@0.8.0
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.7
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
